receivers:
  otlp:
    protocols:
      grpc:
      http:

  # Dummy receiver that's never used, because a pipeline is required to have one.
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: "localhost:12345"

exporters:
  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

service:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [spanmetrics, batch]
      exporters: [jaeger]

    metrics:
      receivers: [ otlp/spanmetrics ]
      exporters: [ prometheus ]