/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A version number made of a "major" and a "minor" version numbers.
 *
 * To be detailed.
 */
export type Version = string;
/**
 * Number of seconds since UNIX Epoch time (1970/01/01 00:00:00)
 */
export type Timestamp = number;
/**
 * A domain name
 */
export type Domain = string;
/**
 * The base64 representation of a data signature
 */
export type Signature = string;
/**
 * A Generated Unique Identifier dedicated to a placement and an Addressable Content
 */
export type TransactionId = string;
/**
 * A domain name
 */
export type TransmissionReceiver = string;
/**
 * A GUID associated to a potential Addressable Content.
 */
export type TransmissionContentId = string;
/**
 * List of pairs of one content_id and one transaction_id. It is possible to have many content_ids for one transaction_ids. In this case, there would be N pairs of 'contents'.
 */
export type TransmissionContents = {
  content_id: TransmissionContentId;
  transaction_id: TransactionId;
}[];
/**
 * Equals "success" if the DSP signed the Transmission and returns it to the sender.<br /> Equals "error_bad_request" if the receiver doesn't understand or see inconsistency in the Transmission Request.<br /> Equals "error_cannot_process" if the receiver failed to use the data of the Transmission Request properly.
 */
export type TransmissionStatus = 'success' | 'error_bad_request' | 'error_cannot_process';
/**
 * The details of the status. It can be empty for "success" but it should detail the reason(s) in case of an error.
 */
export type TransmissionDetails = string;
/**
 * No parameter expected to call this endpoint
 */
export type Get3PcRequest = null;
/**
 * No parameter expected to call this endpoint
 */
export type GetIdentityRequest = null;
/**
 * List of identifiers
 */
export type Identifiers = Identifier[];
/**
 * The URL that the user should be be redirected to, to provide response data
 */
export type ReturnUrl = string;
/**
 * The response code used on a redirect endpoint<br>While REST endpoints can use HTTP codes to communicate the state of the response, redirect endpoints are limited to `30x` HTTP codes.<br>To address this problem, this property is used to contain the same HTTP code as the one that would be returned by a REST endpoint.
 */
export type ResponseCode = number;

/**
 * ** Please ignore **
 * Only needed to have an entry point for generating all interfaces together
 */
export interface _ {
  'audit-log'?: AuditLog;
  'delete-ids-prefs-request'?: DeleteIdsPrefsRequest;
  'delete-ids-prefs-response'?: DeleteIdsPrefsResponse;
  domain?: Domain;
  error?: Error;
  'get-3pc-request'?: Get3PcRequest;
  'get-3pc-response'?: Get3PcResponse;
  'get-identity-request'?: GetIdentityRequest;
  'get-identity-response'?: GetIdentityResponse;
  'get-ids-prefs-request'?: GetIdsPrefsRequest;
  'get-ids-prefs-response'?: GetIdsPrefsResponse;
  'get-new-id-request'?: GetNewIdRequest;
  'get-new-id-response'?: GetNewIdResponse;
  identifier?: Identifier;
  identifiers?: Identifiers;
  'ids-and-optional-preferences'?: IdsAndOptionalPreferences;
  'ids-and-preferences'?: IdsAndPreferences;
  'message-base'?: MessageBase;
  'open-rtb-bid-request'?: OpenRtbBidRequest;
  'open-rtb-bid-response'?: OpenRtbBidResponse;
  'post-ids-prefs-request'?: PostIdsPrefsRequest;
  'post-ids-prefs-response'?: PostIdsPrefsResponse;
  'post-seed-request'?: PostSeedRequest;
  'post-seed-response'?: PostSeedResponse;
  'post-sign-preferences-request'?: PostSignPreferencesRequest;
  'preferences-data'?: PreferencesData;
  preferences?: Preferences;
  'proxy-post-ids-prefs-response'?: ProxyPostIdsPrefsResponse;
  'redirect-delete-ids-prefs-request'?: RedirectDeleteIdsPrefsRequest;
  'redirect-delete-ids-prefs-response'?: RedirectDeleteIdsPrefsResponse;
  'redirect-get-ids-prefs-request'?: RedirectGetIdsPrefsRequest;
  'redirect-get-ids-prefs-response'?: RedirectGetIdsPrefsResponse;
  'redirect-post-ids-prefs-request'?: RedirectPostIdsPrefsRequest;
  'redirect-post-ids-prefs-response'?: RedirectPostIdsPrefsResponse;
  'response-code'?: ResponseCode;
  'return-url'?: ReturnUrl;
  seed?: Seed;
  signature?: Signature;
  source?: Source;
  'standalone-bid-request'?: StandaloneBidRequest;
  'standalone-bid-response'?: StandaloneBidResponse;
  'test-3pc'?: Test3Pc;
  timestamp?: Timestamp;
  transaction_id?: TransactionId;
  'transmission-content_id'?: TransmissionContentId;
  'transmission-contents'?: TransmissionContents;
  'transmission-details'?: TransmissionDetails;
  'transmission-receiver'?: TransmissionReceiver;
  'transmission-request'?: TransmissionRequest;
  'transmission-response'?: TransmissionResponse;
  'transmission-response-standalone'?: TransmissionResponseStandalone;
  'transmission-result'?: TransmissionResult;
  'transmission-status'?: TransmissionStatus;
  'unsigned-preferences'?: UnsignedPreferences;
  version?: Version;
}
/**
 * An Audit Log gathers the necessary data to audit a Transaction (via Transmission) for a given Addressable Content
 */
export interface AuditLog {
  version?: Version;
  data: IdsAndPreferences;
  seed: Seed;
  transaction_id: TransactionId;
  /**
   * The list of Transmission Results that participated to the generation of the content. This list is chronologically ordered.
   */
  transmissions: TransmissionResult[];
}
/**
 * A list of identifiers and some preferences
 */
export interface IdsAndPreferences {
  preferences: Preferences;
  identifiers: Identifier[];
}
/**
 * The current preferences of the user
 */
export interface Preferences {
  version: Version;
  data: PreferencesData;
  source: Source;
}
/**
 * Preferences data
 */
export interface PreferencesData {
  /**
   * Whether the user accepts (`true`) or not (`false`) that their browsing is used for personalization
   */
  use_browsing_for_personalization: boolean;
}
/**
 * Source of data representing what contracting party created and signed the data
 */
export interface Source {
  timestamp: Timestamp;
  domain: Domain;
  signature: Signature;
}
/**
 * A pseudonymous identifier generated for a web user
 */
export interface Identifier {
  version: Version;
  /**
   * The identifier type, identifier of type `paf_browser_id` is mandatory and is "pivot"
   */
  type: 'paf_browser_id';
  /**
   * If set to `false`, means the identifier has not yet been persisted as a cookie.<br>Otherwise, means this identifier is persisted as a PAF cookie<br>(default value = `true` meaning if the property is omitted the identifier *is* persisted)
   */
  persisted?: boolean;
  /**
   * The identifier value
   */
  value: string;
  source: Source;
}
/**
 * The Seed gathers data related to the Addressable Content and sign them.
 */
export interface Seed {
  version: Version;
  transaction_ids: TransactionId[];
  publisher: Domain;
  source: Source;
}
export interface TransmissionResult {
  version: Version;
  receiver: TransmissionReceiver;
  contents: TransmissionContents;
  status: TransmissionStatus;
  details: TransmissionDetails;
  source: Source;
}
/**
 * DELETE /v1/ids-prefs request
 */
export interface DeleteIdsPrefsRequest {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
}
/**
 * A success code is returned in case of successful deletion of the identifiers and preferences
 */
export interface DeleteIdsPrefsResponse {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
  body?: IdsAndOptionalPreferences;
}
/**
 * A list of identifiers and optionally, some preferences
 */
export interface IdsAndOptionalPreferences {
  preferences?: Preferences;
  identifiers: Identifier[];
}
/**
 * The description of an error
 */
export interface Error {
  /**
   * The error message
   */
  message: string;
}
/**
 * GET /v1/3pc response
 */
export interface Get3PcResponse {
  '3pc': Test3Pc;
}
/**
 * A cookie temporarily set to test support of 3d party cookies
 */
export interface Test3Pc {
  timestamp: Timestamp;
}
/**
 * GET /v1/identity response
 */
export interface GetIdentityResponse {
  /**
   * The name of the contracting party, since the domain may not reflect the company name.
   *
   */
  name: string;
  /**
   * The type of contracting party in the PAF ecosystem
   */
  type: 'vendor' | 'operator';
  version: Version;
  /**
   * Email address to contact the contracting party
   */
  dpo_email: string;
  /**
   * URL of the privacy policy of the contracting party
   */
  privacy_policy_url: string;
  /**
   * List of public keys the contracting party used or is using for signing data and messages
   */
  keys: {
    /**
     * Public key string value
     */
    key: string;
    start: Timestamp;
    end?: Timestamp;
  }[];
}
/**
 * GET /v1/ids-prefs request
 */
export interface GetIdsPrefsRequest {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
}
/**
 * GET /v1/ids-prefs response
 */
export interface GetIdsPrefsResponse {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
  body: IdsAndOptionalPreferences;
}
/**
 * GET /v1/new-id request
 */
export interface GetNewIdRequest {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
}
/**
 * GET /v1/new-id response
 */
export interface GetNewIdResponse {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
  body: {
    identifiers: Identifier[];
  };
}
/**
 * The base properties of a request or response to/from an operator
 */
export interface MessageBase {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
}
/**
 * An Open RTB Bid Request according to the 2.5 OpenRTB specification. OpenRTB specifies fields unused for the integration of the Transmission Request. Therefore, they are omitted on purpose here.
 */
export interface OpenRtbBidRequest {
  imp: {
    /**
     * Placeholder for exchange-specific extensions to OpenRTB.
     */
    ext: {
      /**
       * Ext field accessible for PrebidJS RTD
       */
      data: {
        /**
         * Dedicated object for PAF as an extension.
         */
        paf: {
          transaction_id: TransactionId;
        };
      };
    };
    [k: string]: unknown | undefined;
  }[];
  user: {
    /**
     * Placeholder for exchange-specific extensions to OpenRTB.
     */
    ext: {
      eids: {
        source: string;
        uids: {
          /**
           * Equals 'paf'. eids spec: Source or technology provider responsible for the set of included IDs. Expressed as a top-level domain.
           */
          source: string;
          /**
           * Equal to 1 for the element of PAF Data.
           * Type of user agent the match is from. It is highly recommended to set this, as many DSPs separate app-native IDs from browser-based IDs and require a type value for ID resolution.
           */
          atype: number;
          /**
           * Equal to the PAF Id for the element of the PAF Data.
           * Cookie or platform-native identifier.
           */
          id: string;
          /**
           * Placeholder for exchange-specific extensions to OpenRTB.
           */
          ext?: {
            version: Version;
            /**
             * Equals 'paf_browser_id'
             */
            type: string;
            source: Source;
          };
        }[];
        /**
         * Placeholder for exchange-specific extensions to OpenRTB.
         */
        ext: {
          preferences: Preferences;
        };
      }[];
      /**
       * Object dedicated to PAF
       */
      paf: {
        /**
         * Object dedicated to PAF transmission
         */
        transmission: {
          seed: Seed;
          parents?: TransmissionResult[];
        };
      };
    };
    [k: string]: unknown | undefined;
  };
}
/**
 * An Open RTB Bid Response according to the 2.5 OpenRTB specification. OpenRTB specifies fields unused in the integration of the Transmission Response. Therefore, they are omitted on purpose here.
 */
export interface OpenRtbBidResponse {
  /**
   * Placeholder for exchange-specific extensions to OpenRTB.
   */
  ext: {
    /**
     * Dedicated object for PAF as an extension.
     */
    paf: {
      transmission: TransmissionResponse;
    };
  };
  /**
   * Represents a specific seat that provides at least one bid.
   */
  seatbid: {
    seat?: string;
    /**
     * A bid for an impression.
     */
    bid?: {
      /**
       * Placeholder for exchange-specific extensions to OpenRTB.
       */
      ext: {
        /**
         * Dedicated object for PAF as an extension.
         */
        paf: {
          content_id: TransmissionContentId;
        };
      };
      [k: string]: unknown | undefined;
    }[];
  }[];
}
export interface TransmissionResponse {
  version: Version;
  receiver: TransmissionReceiver;
  contents: TransmissionContents;
  status: TransmissionStatus;
  details: TransmissionDetails;
  source: Source;
  children: TransmissionResponse[];
}
/**
 * POST /v1/ids-prefs request
 */
export interface PostIdsPrefsRequest {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
  body: IdsAndPreferences;
}
/**
 * POST /v1/ids-prefs response
 */
export interface PostIdsPrefsResponse {
  sender: Domain;
  receiver: Domain;
  timestamp: Timestamp;
  signature: Signature;
  body: IdsAndPreferences;
}
/**
 * POST /paf-proxy/v1/seed request
 */
export interface PostSeedRequest {
  data: IdsAndPreferences;
  transaction_ids: TransactionId[];
}
/**
 * POST /paf-proxy/v1/seed response
 */
export interface PostSeedResponse {
  version: Version;
  transaction_ids: TransactionId[];
  publisher: Domain;
  source: Source;
}
/**
 * POST /paf-proxy/v1/sign/prefs request
 */
export interface PostSignPreferencesRequest {
  unsignedPreferences: UnsignedPreferences;
  identifiers: Identifiers;
}
/**
 * The current preferences of the user before they are signed
 */
export interface UnsignedPreferences {
  version: Version;
  data: PreferencesData;
}
/**
 * POST /paf-proxy/v1/ids-prefs response
 */
export interface ProxyPostIdsPrefsResponse {
  /**
   * To URL to call on the operator
   */
  url: string;
  payload: PostIdsPrefsRequest;
}
/**
 * GET /v1/redirect/delete-ids-prefs request
 */
export interface RedirectDeleteIdsPrefsRequest {
  returnUrl: ReturnUrl;
  request: DeleteIdsPrefsRequest;
}
/**
 * GET /v1/redirect/delete-ids-prefs response
 */
export interface RedirectDeleteIdsPrefsResponse {
  code: ResponseCode;
  response?: DeleteIdsPrefsResponse;
  error?: Error;
}
/**
 * GET /v1/redirect/get-ids-prefs request
 */
export interface RedirectGetIdsPrefsRequest {
  returnUrl: ReturnUrl;
  request: GetIdsPrefsRequest;
}
/**
 * GET /v1/redirect/get-ids-prefs response
 */
export interface RedirectGetIdsPrefsResponse {
  code: ResponseCode;
  response?: GetIdsPrefsResponse;
  error?: Error;
}
/**
 * GET /v1/redirect/post-ids-prefs request
 */
export interface RedirectPostIdsPrefsRequest {
  returnUrl: ReturnUrl;
  request: PostIdsPrefsRequest;
}
/**
 * GET /v1/redirect/post-ids-prefs response
 */
export interface RedirectPostIdsPrefsResponse {
  code: ResponseCode;
  response?: PostIdsPrefsResponse;
  error?: Error;
}
/**
 * A non-Open RTB Bid Request (with custom format) that includes a Transmission Request in standalone
 */
export interface StandaloneBidRequest {
  paf_transmission?: TransmissionRequest;
  [k: string]: unknown | undefined;
}
/**
 * The request sent from a Sender to a Receiver for sharing PAF data for a set of Addressable Content
 */
export interface TransmissionRequest {
  seed: Seed;
  data: IdsAndPreferences;
  /**
   * The list of Transmission Results representing the path of in-progress Transmissions for generating this Transmission Request. This list is chronologically ordered.
   */
  parents?: TransmissionResult[];
}
/**
 * A non-Open RTB Bid Request (with custom format) that includes a Transmission Response in standalone
 */
export interface StandaloneBidResponse {
  paf_transmission?: TransmissionResponse;
  [k: string]: unknown | undefined;
}
/**
 * A response in an custom communication for acknowledging the use (or not) of PAF data between two Contracting Parties for many Addressable Contents
 */
export interface TransmissionResponseStandalone {}
