export enum NodeErrorType {
  INVALID_RETURN_URL = 'INVALID_RETURN_URL',
  VERIFICATION_FAILED = 'VERIFICATION_FAILED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_ORIGIN = 'INVALID_ORIGIN',
  INVALID_REFERER = 'INVALID_REFERER',
  INVALID_JSON_BODY = 'INVALID_JSON_BODY',
  UNAUTHORIZED_OPERATION = 'UNAUTHORIZED_OPERATION',
  INVALID_QUERY_STRING = 'INVALID_QUERY_STRING',
  UNKNOWN_SIGNER = 'UNKNOWN_SIGNER',
  RESPONSE_TIMEOUT = 'RESPONSE_TIMEOUT',
}

export interface NodeError {
  type: NodeErrorType;
  details: string;
}
